- name: Render the Jinja2 template and store it in a variable
  template:
    src: script_template.j2
    dest: /tmp/ssl_script.sh  # 원격 서버에 임시로 파일 생성
    mode: '0755'

- name: Execute the rendered script using raw
  raw: "/tmp/ssl_script.sh"

- name: Remove the script after execution
  raw: "rm -f /tmp/ssl_script.sh"