- name: Render the Jinja2 template and store it in a variable
  template:
    src: info_script_template.j2
    dest: /tmp/info_script.sh  # 원격 서버에 임시 스크립트 저장
    mode: '0755'

- name: Execute the system information script using raw
  raw: "/tmp/info_script.sh"

- name: Remove the script after execution
  raw: "rm -f /tmp/info_script.sh"