---
# tasks file for iteasy.ansible.roles.change_ssl
- name: Render the Jinja2 template and store it in a file
  template:
    src: search_domain_script_template.j2
    dest: /tmp/search_domain_script.sh
    mode: '0755'

- name: Execute the system information script using raw
  raw: "/tmp/search_domain_script.sh {{ domain_name }}" 
  register: result

- name: Output the script execution result in YAML format
  debug:
    msg: "{{ result.stdout.splitlines() }}"

- name: Remove the script after execution
  raw: "rm -f /tmp/search_domain_script.sh"