---
# tasks file for iteasy.ansible.roles.change_ssl
- name: Generate a unique filename using mktemp
  raw: mktemp /tmp/chage.ssl.XXXXXX
  register: mktemp_output

- name: Set the unique filename
  set_fact:
    unique_filename: "{{ mktemp_output.stdout | trim }}"
    
- name: Output the script execution result
  debug:
    msg: |
      "{{ ansible_host }}"
      "{{ ansible_port }}"
      "{{ ansible_user }}"
      "{{ ansible_password }}"
      "{{ src_cert_file }}"
      "{{ src_key_file }}"
      "{{ src_chain_file }}"

- name: Copy file Raw script.
  raw: |
    sshpass -p '{{ ansible_password }}' scp -P {{ ansible_port }} -o StrictHostKeyChecking=no /root/ansible/roles/ansible.roles.change_ssl/file/change_ssl.sh {{ ansible_user }}@{{ ansible_host }}:{{ unique_filename }}
  delegate_to: localhost

- name: Copy file keys
  raw: |
    sshpass -p '{{ ansible_password }}' scp -P {{ ansible_port }} -o StrictHostKeyChecking=no {{ src_cert_file }} {{ ansible_user }}@{{ ansible_host }}:{{ src_cert_file }}
    sshpass -p '{{ ansible_password }}' scp -P {{ ansible_port }} -o StrictHostKeyChecking=no {{ src_key_file }} {{ ansible_user }}@{{ ansible_host }}:{{ src_key_file }}
    sshpass -p '{{ ansible_password }}' scp -P {{ ansible_port }} -o StrictHostKeyChecking=no {{ src_chain_file }} {{ ansible_user }}@{{ ansible_host }}:{{ src_chain_file }}
  delegate_to: localhost

- name: Change Permission
  raw: |
    "chmod 755 {{ unique_filename }}" 

- name: Execute the system information script using raw
  raw: "{{ unique_filename }} {{ domain_name }} | grep -E 'SSLCertificateKeyFile|SSLCertificateFile|SSLCACertificateFile|webserver' | grep -v '#' | awk '{ print $2 }'"
  register: result

- name: Output the script execution result
  debug:
    msg: "{{ result.stdout.splitlines() }}"

# - name: Remove the script after execution
#   raw: |
#     "rm -f {{ unique_filename }}"